### PR TITLE
add myself as maintainer [skip ci]

### PR DESCRIPTION
**Pull request by carlodri**
since I'm a user of this package, I would like to help in maintaining it.

### CODE REVIEW

**Comment by carlodri** [comment]
@conda-forge/core can someone merge please?

**Comment by isuruf** [comment]
@carlodri, please give the maintainers some time before asking core

**Comment by ocefpaf** [comment]
> @carlodri, please give the maintainers some time before asking core

Indeed. But in this case the main maintainer is @nehaljwani and he is quite busy with his day job. I presume he'll be happy to share this feedstock responsibilities with @carlodri. Let's get this merged!

**Comment by carlodri** [comment]
@isuruf @ocefpaf sorry for my impatience, I just didn't want to leave PRs "dangling around"... 

Next time I promise I will wait some more time before harassing core... 😉

**Pull request merged**
